# Python CircleCI 2.0 configuration file
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
        auth:
            username: xian8290
            password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      #Step 2: Set up docker containers
      - setup_remote_docker
      # step 3 start docker containers
      - run:
          name: Start containers and check that client can talke to kafka
          command: |
            set -x
            docker-compose up -d
             docker run --network container:client \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused broker
      #step 4: copy repo to python container
      - run:
          name: copy code to python container
          command: |
            docker cp ~/repo client:$HOME/portfolio
      # Step 5: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            docker exec client pip install -r $HOME/portfolio/requirements.txt
      #Step 6: Start test Kafka topic
      - run:
          name: start test kafka topic
          command: |
            docker exec client python $HOME/portfolio/tests/setup_test_topic.py
      # Step 7: run tests
      - run:
          name: run tests
          command: |
            docker exec client pytest -v --cov=portfolio $HOME/portfolio/
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - docker-hub-creds            