# Python CircleCI 2.0 configuration file
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5
        auth:
            username: xian8290
            password: $DOCKERHUB_PASSWORD

      - image: confluentinc/cp-zookeeper:6.0.0
        auth:
          username: xian8290
          password: $DOCKERHUB_PASSWORD
        hostname: zookeeper
        container_name: zookeeper
        ports:
          - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000


    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      #wait for zookeeper to be ready
      - run:
          name: Waiting for zookeeper to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 2181 && echo Success && exit 0
              sleep 10
            done
            echo Failed waiting for zookeeper && exit 1
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
      # Step 3: run tests
      - run:
          name: run tests
          command: |
            python -m pytest -v --cov
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - docker-hub-creds            