# Python CircleCI 2.0 configuration file
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
        auth:
            username: xian8290
            password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            conda config --append channels conda-forge
            conda create --name portfolio_venv --file requirements.txt
            pip install confluent-kafka[avro]
            pip install riak
            source activate portfolio_venv
      # Step 3: run tests
      - run:
          name: run tests
          command: |
            source activate portfolio_venv
            python -m pytest -v --cov=google_scraper
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - docker-hub-creds            