# Python CircleCI 2.0 configuration file
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
        auth:
            username: xian8290
            password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      #Step 2: Set up docker containers
      - setup_remote_docker
      # step 3 start docker containers
      - run:
          name: Start containers 
          command: |
            set -x
            docker-compose up -d
      - run:
          name: clone code to python container
          command: |
            docker exec client git clone git@github.com:Cbflessner/portfolio.git
      # Step 4: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            docker exec client pip install -r repo/requirements.txt
      # Step 3: run tests
      - run:
          name: run tests
          command: |
            docker exec client python -m pytest -v --cov=portfolio tests/
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - docker-hub-creds            