# Python CircleCI 2.0 configuration file
jobs:
  build:
    docker:
      - image: circleci/python:3.8
        auth:
            username: xian8290
            password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo apt-get install python3.8-venv
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest -v --cov
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - docker-hub-creds            