# Python CircleCI 2.0 configuration file
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
        auth:
            username: xian8290
            password: $DOCKERHUB_PASSWORD

    working_directory: ~/portfolio

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      #Step 2: Set up docker containers
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install Docker Compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      # step 3 start docker containers
      - run:
          name: Start containers
          command: |
            set -x
            docker-compose up -d
      - run:
          name: start test kafka topic
          command: |
            docker exec producer python /portfolio/tests/setup_test_topic.py
      # Step 7: run tests
      - run:
          name: run tests
          command: |
            docker exec producer pytest -v 
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - docker-hub-creds            