# Python CircleCI 2.0 configuration file
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5
        auth:
            username: xian8290
            password: $DOCKERHUB_PASSWORD

      - image: confluentinc/cp-zookeeper:6.0.0
        auth:
          username: xian8290
          password: $DOCKERHUB_PASSWORD
        hostname: zookeeper
        container_name: zookeeper
        ports:
          - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000


       