FROM python:3.8.5

RUN groupadd -g 998 producer && \
    useradd -r -u 998 -g producer producer -m -d /home/portfolio

WORKDIR /home/portfolio

COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt
RUN apt-get update
RUN apt-get install nano

COPY kafka kafka
COPY avro avro
COPY data data
COPY web_scrapers web_scrapers
RUN mv kafka/producer.py kafka/boot_producer.sh ./

RUN chown -R producer:producer ./
USER producer

EXPOSE 5432
ENTRYPOINT ["./boot_producer.sh"]


