FROM python:3.8.5

RUN groupadd -g 998 nwe && \
    useradd -r -u 998 -g nwe nwe -m -d /home/portfolio

WORKDIR /home/portfolio

COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt
RUN apt-get update
RUN apt-get install nano

COPY ui ui
RUN chmod +x /home/portfolio/ui/boot_client.sh

ENV FLASK_APP next_word_engine.py

RUN chown -R nwe:nwe /home/portfolio

EXPOSE 5000
ENTRYPOINT ["./ui/boot_client.sh"]